name: FlyUI
main: FlyUI\Main
api: [3.0.0, 4.0.0]
version: 2.0
author: Alfiangaming189
github: https://github.com/XBadboy

commands:
 fly:
  description: §eOpen Your Menu FlyUI_By_Alfiangaming
  permission: fly.commands
